-- Scripts/tests/test_spy.lua
local T = dofile(_G.SCRIPTS_PATH .. "\\tests\\run_test.lua")
T.reset()

local Reg = _G.Reg
local spy = Reg.module("actions.spy")

T.run("module registered", function()
	T.assert_not_nil(spy)
end)

T.run("is ActionBase subclass", function()
	T.assert_not_nil(spy.enable)
	T.assert_not_nil(spy.disable)
	T.assert_not_nil(spy.hook)
	T.assert_not_nil(spy.unhook)
	T.assert_not_nil(spy.log)
end)

T.run("state keys have correct types", function()
	T.assert_eq(type(spy.state.config), "table", "config is table")
	T.assert_eq(type(spy.state.enabled), "boolean", "enabled is boolean")
	T.assert_eq(type(spy.state.in_hook), "boolean", "in_hook is boolean")
	T.assert_eq(type(spy.state.call_stack), "table", "call_stack is table")
	T.assert_eq(type(spy.state.wrapper_mode), "boolean", "wrapper_mode is boolean")
	T.assert_eq(type(spy.state.call_count), "number", "call_count is number")
end)

T.run("config has correct defaults", function()
	T.assert_eq(spy.state.config.source_substr, "", "source_substr default")
	T.assert_eq(spy.state.config.func_name, "", "func_name default")
	T.assert_eq(spy.state.config.capture_stack, true, "capture_stack default")
	T.assert_eq(spy.state.config.cache_logs, true, "cache_logs default")
end)

T.run("private helpers exist as module methods", function()
	T.assert_not_nil(spy._class_of_self, "has _class_of_self")
	T.assert_not_nil(spy._capture_params, "has _capture_params")
	T.assert_not_nil(spy._capture_traceback, "has _capture_traceback")
	T.assert_not_nil(spy._path_to_module, "has _path_to_module")
	T.assert_not_nil(spy._parse_source, "has _parse_source")
	T.assert_not_nil(spy._start_wrapper_mode, "has _start_wrapper_mode")
	T.assert_not_nil(spy._stop_wrapper_mode, "has _stop_wrapper_mode")
	T.assert_not_nil(spy._create_spy_handler, "has _create_spy_handler")
end)

T.run("public API methods exist", function()
	T.assert_not_nil(spy.set_target, "has set_target")
	T.assert_not_nil(spy.start, "has start")
	T.assert_not_nil(spy.stop, "has stop")
	T.assert_not_nil(spy.is_enabled, "has is_enabled")
	T.assert_not_nil(spy.get_stats, "has get_stats")
	T.assert_not_nil(spy.clear_cache, "has clear_cache")
	T.assert_not_nil(spy.list_G_instances, "has list_G_instances")
end)

T.run("set_target updates config", function()
	spy:set_target("some_module", "some_func")
	T.assert_eq(spy.state.config.source_substr, "some_module", "source updated")
	T.assert_eq(spy.state.config.func_name, "some_func", "func updated")
	spy:set_target("", "")
end)

T.run("_path_to_module converts correctly", function()
	local result = spy:_path_to_module("hexm/client/test.lua")
	T.assert_eq(result, "hexm.client.test", "forward slash path")
	local result2 = spy:_path_to_module("hexm\\client\\test.lua")
	T.assert_eq(result2, "hexm.client.test", "backslash path")
end)

T.run("_parse_source splits correctly", function()
	local r1 = spy:_parse_source("some.module:ClassName")
	T.assert_eq(r1.path, "some.module", "path extracted")
	T.assert_eq(r1.class, "ClassName", "class extracted")
	local r2 = spy:_parse_source("some.module")
	T.assert_eq(r2.path, "some.module", "path only")
	T.assert_eq(r2.class, nil, "no class")
end)

T.run("is_enabled returns false when stopped", function()
	T.assert_false(spy:is_enabled(), "not enabled initially")
end)

T.run("get_stats returns valid table", function()
	local stats = spy:get_stats()
	T.assert_eq(type(stats), "table", "returns table")
	T.assert_eq(type(stats.is_enabled), "boolean", "has is_enabled")
	T.assert_eq(type(stats.call_count), "number", "has call_count")
	T.assert_eq(type(stats.unique_count), "number", "has unique_count")
end)

T.summary()
