-- Scripts/tests/test_parry_online.lua
local T = dofile("C:\\temp\\Where Winds Meet\\Scripts\\tests\\run_test.lua")
T.reset()

local Reg = _G.Reg
local parry_online = Reg.module("actions.parry_online")

T.run("module registered", function()
	T.assert_not_nil(parry_online)
end)

T.run("is ActionBase subclass", function()
	T.assert_not_nil(parry_online.state, "has state")
	T.assert_not_nil(parry_online.enable, "has enable")
	T.assert_not_nil(parry_online.disable, "has disable")
	T.assert_not_nil(parry_online.is_enabled, "has is_enabled")
end)

T.run("state keys have correct types", function()
	T.assert_eq(type(parry_online.state.log_enabled), "boolean", "log_enabled is boolean")
	T.assert_eq(type(parry_online.state.auto_parry_on_bone_hit), "boolean", "auto_parry_on_bone_hit is boolean")
	T.assert_eq(type(parry_online.state.save_npc_learned), "boolean", "save_npc_learned is boolean")
	T.assert_eq(type(parry_online.state.predictions), "table", "predictions is table")
	T.assert_eq(type(parry_online.state.npc_learned), "table", "npc_learned is table")
	T.assert_eq(type(parry_online.state.seen_events), "table", "seen_events is table")
	T.assert_eq(type(parry_online.state.event_counts), "table", "event_counts is table")
end)

T.run("hook lifecycle - listenable", function()
	parry_online:disable()
	T.assert_false(parry_online:is_hooked("listenable"), "starts unhooked")
	parry_online:hook("listenable")
	T.assert_true(parry_online:is_hooked("listenable"), "hooked after hook()")
	parry_online:unhook("listenable")
	T.assert_false(parry_online:is_hooked("listenable"), "unhooked after unhook()")
end)

T.run("hook lifecycle - set_ex_data", function()
	parry_online:hook("set_ex_data")
	T.assert_true(parry_online:is_hooked("set_ex_data"), "hooked")
	parry_online:unhook("set_ex_data")
	T.assert_false(parry_online:is_hooked("set_ex_data"), "unhooked")
end)

T.run("hook lifecycle - on_bone_hit", function()
	parry_online:hook("on_bone_hit")
	T.assert_true(parry_online:is_hooked("on_bone_hit"), "hooked")
	parry_online:unhook("on_bone_hit")
	T.assert_false(parry_online:is_hooked("on_bone_hit"), "unhooked")
end)

T.run("hook lifecycle - do_attack", function()
	parry_online:hook("do_attack")
	T.assert_true(parry_online:is_hooked("do_attack"), "hooked")
	parry_online:unhook("do_attack")
	T.assert_false(parry_online:is_hooked("do_attack"), "unhooked")
end)

T.run("enable/disable lifecycle", function()
	parry_online:disable()
	T.assert_false(parry_online:is_enabled())

	parry_online:enable()
	T.assert_true(parry_online:is_enabled())
	T.assert_true(parry_online:is_hooked("listenable"), "listenable active after enable")
	T.assert_true(parry_online:is_hooked("set_ex_data"), "set_ex_data active after enable")
	T.assert_true(parry_online:is_hooked("on_bone_hit"), "on_bone_hit active after enable")
	T.assert_true(parry_online:is_hooked("do_attack"), "do_attack active after enable")

	parry_online:disable()
	T.assert_false(parry_online:is_enabled())
	T.assert_false(parry_online:is_hooked("listenable"), "all unhooked after disable")
end)

T.run("private helpers exist", function()
	T.assert_not_nil(parry_online._intercept_listenable, "has _intercept_listenable")
	T.assert_not_nil(parry_online._intercept_set_ex_data, "has _intercept_set_ex_data")
	T.assert_not_nil(parry_online._intercept_on_bone_hit, "has _intercept_on_bone_hit")
	T.assert_not_nil(parry_online._intercept_do_attack, "has _intercept_do_attack")
	T.assert_not_nil(parry_online._try_predict_behit, "has _try_predict_behit")
	T.assert_not_nil(parry_online._load_npc_learned, "has _load_npc_learned")
	T.assert_not_nil(parry_online._save_npc_learned, "has _save_npc_learned")
end)

T.summary()
