-- Scripts/tests/test_sync_observer.lua
local T = dofile(_G.SCRIPTS_PATH .. "\\tests\\run_test.lua")
T.reset()

local Reg = _G.Reg
local sync_obs = Reg.module("actions.sync_observer")

T.run("module registered", function()
	T.assert_not_nil(sync_obs)
end)

T.run("is ActionBase subclass", function()
	T.assert_not_nil(sync_obs.state, "has state")
	T.assert_not_nil(sync_obs.enable, "has enable")
	T.assert_not_nil(sync_obs.disable, "has disable")
	T.assert_not_nil(sync_obs.is_enabled, "has is_enabled")
end)

T.run("state keys have correct types", function()
	T.assert_eq(type(sync_obs.state.log_enabled), "boolean", "log_enabled is boolean")
	T.assert_eq(type(sync_obs.state.seen_events), "table", "seen_events is table")
	T.assert_eq(type(sync_obs.state.event_counts), "table", "event_counts is table")
	T.assert_eq(type(sync_obs.state.event_counts.inbound_rpc), "table", "inbound_rpc is table")
	T.assert_eq(type(sync_obs.state.event_counts.inbound_sync), "table", "inbound_sync is table")
	T.assert_eq(type(sync_obs.state.inbound_methods_ignore), "table", "inbound_methods_ignore is table")
end)

T.run("hook lifecycle - entity_method", function()
	sync_obs:disable()
	T.assert_false(sync_obs:is_hooked("entity_method"), "entity_method starts unhooked")
	sync_obs:hook("entity_method")
	T.assert_true(sync_obs:is_hooked("entity_method"), "entity_method hooked")
	sync_obs:unhook("entity_method")
	T.assert_false(sync_obs:is_hooked("entity_method"), "entity_method unhooked")
end)

T.run("hook lifecycle - do_sync", function()
	sync_obs:disable()
	T.assert_false(sync_obs:is_hooked("do_sync"), "do_sync starts unhooked")
	sync_obs:hook("do_sync")
	T.assert_true(sync_obs:is_hooked("do_sync"), "do_sync hooked")
	sync_obs:unhook("do_sync")
	T.assert_false(sync_obs:is_hooked("do_sync"), "do_sync unhooked")
end)

T.run("hook lifecycle - listenable", function()
	sync_obs:disable()
	T.assert_false(sync_obs:is_hooked("listenable"), "listenable starts unhooked")
	sync_obs:hook("listenable")
	T.assert_true(sync_obs:is_hooked("listenable"), "listenable hooked")
	sync_obs:unhook("listenable")
	T.assert_false(sync_obs:is_hooked("listenable"), "listenable unhooked")
end)

T.run("enable/disable lifecycle", function()
	sync_obs:disable()
	T.assert_false(sync_obs:is_enabled())

	sync_obs:enable()
	T.assert_true(sync_obs:is_enabled())
	T.assert_true(sync_obs:is_hooked("entity_method"), "entity_method active after enable")
	T.assert_true(sync_obs:is_hooked("do_sync"), "do_sync active after enable")
	T.assert_true(sync_obs:is_hooked("listenable"), "listenable active after enable")

	sync_obs:disable()
	T.assert_false(sync_obs:is_enabled())
	T.assert_false(sync_obs:is_hooked("entity_method"), "entity_method inactive after disable")
	T.assert_false(sync_obs:is_hooked("do_sync"), "do_sync inactive after disable")
	T.assert_false(sync_obs:is_hooked("listenable"), "listenable inactive after disable")
end)

T.run("enable resets counters", function()
	sync_obs:enable()
	T.assert_eq(next(sync_obs.state.seen_events), nil, "seen_events cleared on enable")
	T.assert_eq(next(sync_obs.state.event_counts.inbound_rpc), nil, "rpc counts cleared")
	T.assert_eq(next(sync_obs.state.event_counts.inbound_sync), nil, "sync counts cleared")
	sync_obs:disable()
end)

T.run("private helpers exist", function()
	T.assert_not_nil(sync_obs._on_entity_method, "has _on_entity_method")
	T.assert_not_nil(sync_obs._on_inbound_do_sync, "has _on_inbound_do_sync")
	T.assert_not_nil(sync_obs._intercept_listenable, "has _intercept_listenable")
	T.assert_not_nil(sync_obs._format_event, "has _format_event")
	T.assert_not_nil(sync_obs._print_summary, "has _print_summary")
end)

T.summary()
